version: '3.8'

volumes:
  postgres:

services:
  db: 
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: yeahstock
      PGDATABASE: postgres
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - 5432:5432